export enum NavDispatchAction {
    SET_CURRENT_TAB = 'SET_CURRENT_TAB',
    SET_ACTIVE_STEPS = 'SET_ACTIVE_STEPS',
    SET_SCROLL_CATEGORY_ID = 'SET_SCROLL_CATEGORY_ID',
    SET_NOTIFICATION_TARGET_ID = 'SET_NOTIFICATION_TARGET_ID',
    SET_ACTIVE_STEP = 'SET_ACTIVE_STEP',
}