import { ListName, LibraryName, ColumnsDetails, ColumnsRequests, RequestStatus, ColumnsQA, ColumnsCategories, ColumnsDuties, EventType, ColumnsForms, FormStatus, ColumnsRequired, ColumnsDocTypes, ColumnsReqTypes, ColumnsActions, FileValidityAction, ColumnsTrigger, Language, EventPeriodicity, QACategory } from "../enums";
import { ISPColumn } from "../interfaces";

/**columns to create in SP lists during instalation */
export const listColumns: { [key in ListName | LibraryName.Requests]: ISPColumn[] } = {
    [ListName.Details]: [
        { FieldTypeKind: '20', Title: ColumnsDetails.Contact, displayName: 'Kontakt' },
        // { FieldTypeKind: '9', Title: ColumnsDetails.Limit, displayName: 'Limit' },
        // { FieldTypeKind: '9', Title: ColumnsDetails.Withdrawn, displayName: 'Čerpání' },
        { FieldTypeKind: '2', Title: ColumnsDetails.ChannelId, displayName: 'Id kanálu' },
        { FieldTypeKind: '2', Title: ColumnsDetails.CurrentStatus, displayName: 'Stav' },
        { FieldTypeKind: '3', Title: ColumnsDetails.LoanText, displayName: 'Text' },
        { FieldTypeKind: '20', Title: ColumnsDetails.SecondaryContact, displayName: 'Sekundární kontakt' },
        // { FieldTypeKind: '2', Title: ColumnsDetails.ContactDesc, displayName: 'Kontakt popis' },
        // { FieldTypeKind: '2', Title: ColumnsDetails.SecondaryDesc, displayName: 'Sekundární popis' },
        { FieldTypeKind: '2', Title: ColumnsDetails.ChannelStatus, displayName: 'Stav kanálu' },
        { FieldTypeKind: '2', Title: ColumnsDetails.ContactData, displayName: 'Data kontaktu' },
        { FieldTypeKind: '2', Title: ColumnsDetails.SecondaryData, displayName: 'Data sekundárního kontaktu' },
        { FieldTypeKind: '9', Title: ColumnsDetails.Version, displayName: 'Verze' },
    ],
    [ListName.Requests]: [
        { FieldTypeKind: '3', Title: ColumnsRequests.FormData, displayName: 'Data formuláře' },
        { FieldTypeKind: '7', Title: ColumnsRequests.RequestType, lookUpListTitle: ListName.RequestTypes, displayName: 'Typ žádosti' },
        { FieldTypeKind: '6', Title: ColumnsRequests.RequestStatus, Choices: Object.values(RequestStatus), displayName: 'Stav' },
        { FieldTypeKind: '2', Title: ColumnsRequests.FileTemplate, displayName: 'Šablona' },
        { FieldTypeKind: '2', Title: ColumnsRequests.CategoryId, displayName: 'Id kategorie' },
        { FieldTypeKind: '2', Title: ColumnsRequests.FileIds, displayName: 'Id souborů' },
        { FieldTypeKind: '3', Title: ColumnsRequests.ExportData, displayName: 'Export data' },
    ],
    [ListName.QA]: [
        //{ FieldTypeKind: '2', Title: ColumnsQA.Question, displayName: 'Otázka' },
        { FieldTypeKind: '2', Title: ColumnsQA.Answer, displayName: 'Odpověď' },
        { FieldTypeKind: '2', Title: 'Status', displayName: 'Stav' },
        { FieldTypeKind: '6', Title: ColumnsQA.Category, Choices: Object.values(QACategory), displayName: 'Kategorie' },
        { FieldTypeKind: '2', Title: 'FileLink', displayName: 'Soubor' },
        { FieldTypeKind: '2', Title: 'FolderLink', displayName: 'Složka' },
        { FieldTypeKind: '2', Title: 'QuestionFileLink', displayName: 'Soubor otázka' },
        { FieldTypeKind: '2', Title: 'QuestionFolderLink', displayName: 'Složka otázka' },
        { FieldTypeKind: '9', Title: ColumnsQA.Order, displayName: 'Pořadí' },
        { FieldTypeKind: '2', Title: 'Stage', displayName: 'Etapa' },
        { FieldTypeKind: '2', Title: 'Stage_en', displayName: 'Etapa_en' },
        { FieldTypeKind: '2', Title: 'Phase', displayName: 'Fáze' },
        { FieldTypeKind: '2', Title: 'Phase_en', displayName: 'Fáze_en' },
        { FieldTypeKind: '2', Title: ColumnsQA.Answered, displayName: 'Odpověděl' },
        { FieldTypeKind: '2', Title: ColumnsQA.Priority, displayName: 'Priorita' },
        { FieldTypeKind: '3', Title: ColumnsQA.FilesData, displayName: 'FilesData' },
        { FieldTypeKind: '2', Title: ColumnsQA.SubCategory, displayName: 'Podkategorie' },
    ],
    [ListName.Categories]: [
        //{ FieldTypeKind: '2', Title: ColumnsCategories.Folder, displayName: 'Složka' },
        { FieldTypeKind: '2', Title: ColumnsCategories.Stage, displayName: 'Etapa' },
        { FieldTypeKind: '2', Title: ColumnsCategories.Phase, displayName: 'Fáze' },
        { FieldTypeKind: '2', Title: ColumnsCategories.StageEn, displayName: 'Etapa en' },
        { FieldTypeKind: '2', Title: ColumnsCategories.PhaseEn, displayName: 'Fáze en' },
        { FieldTypeKind: '2', Title: ColumnsCategories.CategoryEn, displayName: 'Nadpis en' },
        { FieldTypeKind: '2', Title: ColumnsCategories.Description, displayName: 'Popis' },
        { FieldTypeKind: '2', Title: ColumnsCategories.DescriptionEn, displayName: 'Popis en' },
        { FieldTypeKind: '11', Title: ColumnsCategories.RequiredDocuments, displayName: 'Požadované dokumenty' },
        //{ FieldTypeKind: '4', Title: ColumnsCategories.Deadline, displayName: 'Deadline' },
        { FieldTypeKind: '9', Title: ColumnsCategories.Order, displayName: 'Pořadí' },
        { FieldTypeKind: '2', Title: ColumnsCategories.CategoryStatus, displayName: 'Stav' },
    ],
    [ListName.Duties]: [
        { FieldTypeKind: '2', Title: ColumnsDuties.Date, displayName: 'Datum' },
        { FieldTypeKind: '9', Title: ColumnsDuties.Amount, displayName: 'Částka' },
        { FieldTypeKind: '6', Title: ColumnsDuties.EventType, Choices: Object.values(EventType), displayName: 'Typ' },
        { FieldTypeKind: '2', Title: ColumnsDuties.Currency, displayName: 'Měna' },
        { FieldTypeKind: '2', Title: ColumnsDuties.Instruction, displayName: 'Instrukce' },
        { FieldTypeKind: '6', Title: ColumnsDuties.Category, displayName: 'Kategorie', Choices: ['covenant', 'information'] },
        { FieldTypeKind: '2', Title: ColumnsDuties.EventDescription, displayName: 'Popis' },
        { FieldTypeKind: '2', Title: ColumnsDuties.Note, displayName: 'Poznámka' },
        { FieldTypeKind: '6', Title: ColumnsDuties.Period, Choices: Object.values(EventPeriodicity), displayName: 'Perioda' },
        { FieldTypeKind: '2', Title: ColumnsDuties.EndDate, displayName: 'Konec' },
    ],
    [ListName.Forms]: [
        { FieldTypeKind: '3', Title: ColumnsForms.FormData, displayName: 'Data formuláře' },
        { FieldTypeKind: '2', Title: ColumnsForms.TitleEn, displayName: 'Nadpis en' },
        { FieldTypeKind: '6', Title: ColumnsForms.Status, Choices: Object.values(FormStatus), displayName: 'Stav' },
        { FieldTypeKind: '2', Title: ColumnsForms.FormType, displayName: 'Typ formuláře' },
        { FieldTypeKind: '7', Title: ColumnsForms.Category, lookUpListTitle: ListName.Categories, displayName: 'Kategorie' },
        { FieldTypeKind: '6', Title: ColumnsForms.Language, Choices: Object.values(Language), displayName: 'Jazyk' },
        { FieldTypeKind: '2', Title: ColumnsForms.Completed, displayName: 'Dokončeno' },
        { FieldTypeKind: '9', Title: ColumnsForms.FileId, displayName: 'File Id' },
    ],
    [ListName.Notifications]: [
        { FieldTypeKind: '2', Title: 'Title_en', displayName: 'Nadpis_en' },
        { FieldTypeKind: '8', Title: 'Task', displayName: 'Task' },
        { FieldTypeKind: '8', Title: 'Completed', displayName: 'Completed' },
        { FieldTypeKind: '7', Title: 'Category', lookUpListTitle: ListName.Categories, displayName: 'Category' },
        { FieldTypeKind: '20', Title: 'AssignedTo', displayName: 'AssignedTo', allowMultiple: true }, //TODO add multichoice
        { FieldTypeKind: '20', Title: 'Read', displayName: 'Read', allowMultiple: true },
        { FieldTypeKind: '2', Title: 'Comment', displayName: 'Comment' },
        { FieldTypeKind: '6', Title: 'Status', displayName: 'Status', Choices: ['Akceptovat', 'Dokončit', 'Poslat dál'] },
        { FieldTypeKind: '3', Title: 'Assigned', displayName: 'Assigned' },
        { FieldTypeKind: '2', Title: 'TargetId', displayName: 'TargetId' },
        { FieldTypeKind: '2', Title: 'Link', displayName: 'Link' },
        { FieldTypeKind: '2', Title: 'FileLink', displayName: 'FileLink' },
    ],
    [LibraryName.Requests]: [
        { FieldTypeKind: '2', Title: ColumnsRequests.RequestType, displayName: 'Typ žádosti' },
        { FieldTypeKind: '2', Title: ColumnsRequests.RequestStatus, displayName: 'Stav' },
    ],
    [ListName.RequiredDocuments]: [
        { FieldTypeKind: '2', Title: ColumnsRequired.TitleEn, displayName: 'Nadpis en' },
        //{ FieldTypeKind: '2', Title: ColumnsRequired.FolderPath, displayName: 'Umístění souboru' },
        { FieldTypeKind: '2', Title: ColumnsRequired.FileDesc, displayName: 'Popis souboru' },
        { FieldTypeKind: '7', Title: ColumnsRequired.DocumentType, lookUpListTitle: ListName.DocumentTypes, displayName: 'Typ souboru' },
        { FieldTypeKind: '2', Title: ColumnsRequired.PermittedFormats, displayName: 'Přípustné formáty' },
        { FieldTypeKind: '2', Title: ColumnsRequired.UploadedFile, displayName: 'ID souboru' },
        { FieldTypeKind: '4', Title: ColumnsRequired.Deadline, displayName: 'Deadline' },
        { FieldTypeKind: '2', Title: ColumnsRequired.Status, displayName: 'Stav' },
    ],
    [ListName.DocumentTypes]: [
        { FieldTypeKind: '2', Title: ColumnsDocTypes.TitleEn, displayName: 'Nadpis en' },
        { FieldTypeKind: '2', Title: ColumnsDocTypes.UploadStatus, displayName: 'Stav po nahrání' },
        { FieldTypeKind: '2', Title: ColumnsDocTypes.Permissions, displayName: 'Oprávnění' },
        { FieldTypeKind: '2', Title: ColumnsDocTypes.FolderPath, displayName: 'Složka' },
        { FieldTypeKind: '2', Title: ColumnsDocTypes.FolderPathAfter, displayName: 'Složka po schválení' },
        { FieldTypeKind: '2', Title: ColumnsDocTypes.ValidityStatuses, displayName: 'Stavy platnosti' },
        { FieldTypeKind: '2', Title: ColumnsDocTypes.FolderPathInternal, displayName: 'Interní složka' },
        { FieldTypeKind: '2', Title: ColumnsDocTypes.FolderPathInternalAfter, displayName: 'Interní složka po schválení' }
    ],
    [ListName.RequestTypes]: [
        { FieldTypeKind: '2', Title: ColumnsReqTypes.TitleEn, displayName: 'Nadpis en' },
        { FieldTypeKind: '2', Title: ColumnsReqTypes.FileTemplate, displayName: 'Šablona' },
        { FieldTypeKind: '2', Title: ColumnsReqTypes.FileTemplateEn, displayName: 'Šablona en' },
        { FieldTypeKind: '2', Title: ColumnsReqTypes.Description, displayName: 'Popis' },
        { FieldTypeKind: '2', Title: ColumnsReqTypes.DescriptionEn, displayName: 'Popis en' },
        { FieldTypeKind: '15', Title: ColumnsReqTypes.Stage, displayName: 'Etapa' },
        { FieldTypeKind: '15', Title: ColumnsReqTypes.Fields, displayName: 'Pole' },
        { FieldTypeKind: '8', Title: ColumnsReqTypes.FileAttachments, displayName: 'Příloha' },
        { FieldTypeKind: '2', Title: ColumnsReqTypes.Notification, displayName: 'Notifikace' },
        { FieldTypeKind: '8', Title: ColumnsReqTypes.FileReply, displayName: 'Příloha - odpověď' },
    ],
    [ListName.WorkflowActions]: [
        { FieldTypeKind: '2', Title: ColumnsActions.TitleEn, displayName: 'Nadpis_en' },
        { FieldTypeKind: '3', Title: ColumnsActions.DocumentStatus, displayName: 'Stav dokumentu' },
        { FieldTypeKind: '2', Title: ColumnsActions.Notification, displayName: 'Notifikace' },
        { FieldTypeKind: '2', Title: ColumnsActions.NotificationEn, displayName: 'Notifikace_en' },
        { FieldTypeKind: '2', Title: ColumnsActions.ResultStatus, displayName: 'Cílový stav' },
        { FieldTypeKind: '3', Title: ColumnsActions.DocumentType, displayName: 'Typ souboru' },
        { FieldTypeKind: '8', Title: ColumnsActions.Publish, displayName: 'Publikovat' },
        { FieldTypeKind: '8', Title: ColumnsActions.AllowComment, displayName: 'Povolit komentář' },
        { FieldTypeKind: '2', Title: ColumnsActions.ActionGroups, displayName: 'Skupiny pro akci' },
        { FieldTypeKind: '2', Title: ColumnsActions.Phase, displayName: 'Fáze' },
        { FieldTypeKind: '2', Title: ColumnsActions.NotificationGroups, displayName: 'Skupiny pro notifikaci' },
        { FieldTypeKind: '2', Title: ColumnsActions.Task, displayName: 'Úkol' },
        { FieldTypeKind: '2', Title: ColumnsActions.TaskEn, displayName: 'Úkol_en' },
        { FieldTypeKind: '2', Title: ColumnsActions.TaskGroups, displayName: 'Skupiny pro úkol' },
        { FieldTypeKind: '3', Title: ColumnsActions.ReadPermissions, displayName: 'Oprávnění pro čtení' },
        { FieldTypeKind: '3', Title: ColumnsActions.WritePermissions, displayName: 'Oprávnění upravit' },
        { FieldTypeKind: '6', Title: ColumnsActions.Validity, displayName: 'Nastavení platnosti', Choices: Object.values(FileValidityAction) },
        { FieldTypeKind: '8', Title: ColumnsActions.Reupload, displayName: 'Přepsat soubor' },
        { FieldTypeKind: '8', Title: ColumnsActions.FileLink, displayName: 'Přidat odkaz' },
        { FieldTypeKind: '8', Title: ColumnsActions.OnMajorVersion, displayName: 'Na hlavní verzi' },
    ],
    [ListName.ActionToTrigger]: [
        { FieldTypeKind: '9', Title: ColumnsTrigger.FileId, displayName: 'FileId' },
        { FieldTypeKind: '9', Title: ColumnsTrigger.ActionId, displayName: 'ActionId' },
        { FieldTypeKind: '4', Title: ColumnsTrigger.Processed, displayName: 'Processed' },
        { FieldTypeKind: '9', Title: ColumnsTrigger.Result, displayName: 'Result' },
        { FieldTypeKind: '2', Title: ColumnsTrigger.Comment, displayName: 'Comment' },
    ],
    [ListName.Logs]: [
        { FieldTypeKind: '3', Title: 'Data', displayName: 'Data' },
    ]
};